### PR TITLE
Filter history by the type because previous filter only worked for engli...

### PR DESCRIPTION
**Pull request by lazar2606**
...sh

### CODE REVIEW

**Comment by dregad** [comment]
Thanks for your contribution.

You are using spaces for indentation, please use tabs as per our coding guidelines.

**Comment by dregad** [comment]
@lazar2606 Looks like you're mixing different things here. Please split your commits over multiple branches and submit additional pull requests so that each one fixes a distinct issue.

**Comment by lazar2606** [comment]
I think you need to close the PR #1 and #2, or apply the patch in the PR #1, because all PR solve critical error "an infinite loop ..."

**Comment by lazar2606** [comment]
Can I do something useful to speed up the process?

**Comment by dregad** [comment]
Sorry I did not realize you had updated the PR... Will review and let you know

**Comment by dregad** [comment]
Unfortunately after applying PR #2, this does not merge cleanly anymore. Can you please rebase on top of latest master ?

**Comment by lazar2606** [comment]
Ok

**Comment by dregad** [comment]
Thanks for updating the PR. Having looked at the updated code, I don't think that duplicating core api history_get_events_array() is the right way to address this issue - IMO it would a better approach to fix the InlineHistory_Filter_Entries() function.

That said, I am not sure this is even necessary, as it looks like the issue was already fixed by @ashumkin's commit 9572e228eda36f8d88e9dc31348d44c8a3ec79f0 which I merged earlier today.

Please test and confirm.

**Comment by lazar2606** [comment]
Now everything works well. Thank you.

**Pull request closed without merging**
